### ISSUE TITLE
"TypeError: bot.checkRole is not a function" error

### ISSUE THREAD

**Issue by mszabolcs-dev** [MarinMakers/eyebot#9]
_**bot.checkRole**_ can't be called from nowhere.

> TypeError: bot.checkRole is not a function
    at Object.process (D:\dusty\src\commands\reboot.js:7:13)
    at Client.bot.on (D:\dusty\src\bot.js:54:42)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (D:\dusty\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (D:\dusty\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (D:\dusty\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (D:\dusty\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (D:\dusty\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (D:\dusty\node_modules\ws\lib\websocket.js:137:47)
    at Receiver.dataMessage (D:\dusty\node_modules\ws\lib\receiver.js:409:14)
    at Receiver.getData (D:\dusty\node_modules\ws\lib\receiver.js:347:12)
    at Receiver.startLoop (D:\dusty\node_modules\ws\lib\receiver.js:143:16)
    at Receiver.add (D:\dusty\node_modules\ws\lib\receiver.js:117:10)

**Comment by mszabolcs-dev** [comment]
- **_checkRole_** function needed to be rewritten. 
- The file moved to [/constants/](https://github.com/milesflo/dusty/tree/master/src/constants), so another scope can see/use it.

Any further information check branch - [[rolechecker_bug]](https://github.com/milesflo/dusty/tree/rolechecker_bug)

**Comment by milesflo** [comment]
Issue resolved on master by https://github.com/milesflo/dusty/pull/11
